---

env:
  browser: true
  es2021: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

ignorePatterns:
  - node_modules
  - dist

plugins:
  - react
  - '@typescript-eslint'

rules:
  max-len: [error, code: 100]
  indent: [error, 4]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi: [error, never]
  react/react-in-jsx-scope: off
